### ISSUE TITLE
Scroll navigation

### ISSUE THREAD

**Issue by Recouse** [readium/r2-navigator-swift#122]
I want to implement navigation by scrolling. Like there in the screenshots #94.
Maybe someone has a working solution or some example of how to do that?

**Comment by mickael-menu** [comment]
Do you want the rendering to be horizontal and paginated, or vertical scrolling would work for you?  

We have a vertical scroll mode, but horizontal scrolling won't be possible without modifying the toolkit.

You will need to set `isPagingEnabled` to `false` everywhere it appears in `EPUBReflowableSpreadView`, and disable `snapOffset()` in `utils.js` (maybe by returning the `offset` unchanged).

**Comment by Recouse** [comment]
I want it to be horizontal and paginated. I want the scroll to page with `UISlider`. I need to get the right `Locator` for the slider's value.

**Comment by mickael-menu** [comment]
Okay then it's not supported out of the box, try with the modifications I suggested above.
