### ISSUE TITLE
Customizing the default user settings

### ISSUE THREAD

**Issue by Jokez80** [readium/r2-navigator-swift#158]
We want to change the default value of "Publishers default" to true. I can change in the imported r2-navigator but then you need to remember this if we upgrade and thats not good.

**Comment by mickael-menu** [comment]
I don't think you can override without forking `r2-navigator-swift` at the moment. However, publishers default should already be true by default. Which version of Readium are you using?

https://github.com/readium/r2-navigator-swift/blob/c2183cdf48dd6bd75cfa08319cdb0d1d91257c0d/r2-navigator-swift/EPUB/UserSettings.swift#L32

Until we support this in the API, a workaround could be to set manually the values you want in `UserSettings` and save them during the first launch of your app.

**Comment by Jokez80** [comment]
Ah ok we have not been able to upgrade to next version of Readium yet on iOS (due to Pods) so maybe it all will work when we do that then, great news!
