### ISSUE TITLE
word selection issue

### ISSUE THREAD

**Issue by singhranakumar22gmailcom** [readium/r2-navigator-swift#182]
i am useing readium library for epub  .when i am holding on the first word then it's getting selected and when i am touching and holding  on second word then it's get selected with previous one ,like whole sentence get's selected.

**Comment by mickael-menu** [comment]
Please follow the [bug report issue template](https://github.com/readium/r2-navigator-swift/issues/new?assignees=&labels=&template=bug_report.md&title=) when submitting new issue.

Although I doubt this is in control of Readium, as the `WKWebKit` handles text selection.

**Comment by singhranakumar22gmailcom** [comment]
but this issue is not occurred  when i am loading the html in different wkwebview. can u please help me out.
