### ISSUE TITLE
second page word hi-lighter is not working in landscape

### ISSUE THREAD

**Issue by singhranakumar22gmailcom** [readium/r2-navigator-swift#185]
## Bug Report

i am using readium library for epub and i am trying with javascript to select the word by it's text-id . In landscape it's working fine for 1st page but for second page it's not working. i am using changeTextColor(fragmentId: String) function for hi-lighter , in this function fragmentId printing correctly for second page also, but text is not getting hi-lighted.

Second page word hi-lighter is not working in landscape

* `r2-shared-swift`:
* `r2-streamer-swift`:
* `r2-navigator-swift`:
* `r2-opds-swift`:
* `r2-lcp-swift`:

macOS: 11.2
platform: x86_64
Xcode 12.4
Build version 12D4e

* iOS version: 14.4
* Model (e.g. iPhone 11 Pro Max):  iPhone 12 Pro Max
* Is it an emulator? Yes 

```
func changeTextColor(fragmentId: String) {
          print(fragmentId)
       let scc = "document.getElementById('\(fragmentId)').style.color='#EA4343'; setTimeout(function(){ document.getElementById('\(fragmentId)').style.color = \"#000000\";}, 1500);"
       
       let script = "spread.eval('', \"\(scc.replacingOccurrences(of: "\"", with: "\\\""))\");"

        webView.evaluateJavaScript(script, completionHandler: nil)
}
```

**Comment by mickael-menu** [comment]
Is it with a fixed layout or reflowable publication?

**Comment by singhranakumar22gmailcom** [comment]
i am using fixed layout.

**Comment by mickael-menu** [comment]
I'll take a look to see if I can reproduce this Friday.

**Comment by mickael-menu** [comment]
I checked if `spread.eval()` was working properly using this book: 
[BellaOriginal3.epub.zip](https://github.com/readium/r2-navigator-swift/files/6715469/BellaOriginal3.epub.zip)

Running from the Safari Web Inspector this code:

```javascript
spread.eval("", "document.getElementById('pic').setAttribute('style','opacity:0.2;')")
```

We can see that both images get transparent:

<img width="1319" alt="Screenshot 2021-06-25 at 12 16 57" src="https://user-images.githubusercontent.com/58686775/123410198-53fcc680-d5af-11eb-876c-832affa94e69.png">

If you know the HREF (as in `publication.readingOrder[...].href`) of the particular page you want to run the script on, you can use the first argument:

```javascript
spread.eval("/OEBPS/bella2.xhtml", "document.getElementById('pic').setAttribute('style','opacity:0.8;')")
```

<img width="1319" alt="Screenshot 2021-06-25 at 12 17 08" src="https://user-images.githubusercontent.com/58686775/123410311-77277600-d5af-11eb-81f4-eb1a02612367.png">

So it might be an issue with your JavaScript. I suggest only using single quotes in the JavaScript to avoid the escaping replacement:

```swift
let scc = "document.getElementById('\(fragmentId)').style.color='#EA4343'; setTimeout(function(){ document.getElementById('\(fragmentId)').style.color = '#000000';}, 1500);"
let script = "spread.eval('', \"\(scc)\");"
```

I'm closing this issue, but feel free to continue answering here. I'll reopen it if we find an actual problem in Readium.

**Comment by singhranakumar22gmailcom** [comment]
I implemented `spread.eval()` in spreadview.swift  and it's not working for second page , am i doing right? can we have a session on skype or zoom regarding this ? thank you in advance.

**Comment by singhranakumar22gmailcom** [comment]
Hi Team,

Any update. My app is on completion but because of this issue we are not able to go-live. Kindly help us.

**Comment by mickael-menu** [comment]
> can we have a session on skype or zoom regarding this ?

I'm sorry but I don't have time to offer free (or paid for that matter) support session. And I already checked that `spread.eval()` works properly: https://github.com/readium/r2-navigator-swift/issues/185#issuecomment-868399922

If you can show the problem (with minimal changes) in a fork of [r2-testapp-swift](https://github.com/readium/r2-testapp-swift), I can take a look.
