### ISSUE TITLE
Make internal types Public

### ISSUE THREAD

**Issue by emartinson** [readium/r2-navigator-swift#202]
I tried to subclass EPUBNavigatorViewController, but failed to override some methods as they use internal protocols and types like:
- EPUBSpreadView
- EPUBSpreadViewDelegate

and others. So I can't extend this class and had to use `r2-navigator-swift` as source code copy inside my project instead of external framework.

**Comment by mickael-menu** [comment]
`EPUBNavigatorViewController` is not meant to be subclassed. We don't want to expose too much internal types because it makes it difficult to change the implementation when needed.

Which methods did you want to override and more importantly, what was your use case / goal?

**Comment by emartinson** [comment]
@mickael-menu thank you.
At least:
- spreadViewDidLoad(_ spreadView: EPUBSpreadView)
- spreadView(_ spreadView: EPUBSpreadView, didTapAt point: CGPoint)
- didActivateDecoration
- spreadViewPagesDidChange

I'm trying to implement text highlighting from code and by apple pencil. May be I should use some other features of R2, I'm still investigating.

**Comment by mickael-menu** [comment]
Yeah you don't need to modify `EPUBNavigatorViewController` for this, see my answer in your other issue https://github.com/readium/r2-navigator-swift/issues/201.

I'm closing this issue for now, but you can continue replying in case you encounter blockers while implementing highlighting with `DecorableNavigator` and `SelectableNavigator`.

**Comment by mickael-menu** [comment]
Also to get tap events, you can implement this which is available in the `EPUBNavigatorViewControllerDelegate` https://github.com/readium/r2-navigator-swift/blob/160b7207e0d4a08fd1d7aca65c5a0aa931d56e39/r2-navigator-swift/VisualNavigator.swift#L63

**Comment by emartinson** [comment]
Thank you very much! I got the idea!
