### ISSUE TITLE
Can I ignore single tapgesture for long tapgesture?

### ISSUE THREAD

**Issue by Kofktu** [readium/r2-navigator-swift#23]
Can I ignore single tabs for long tabs?
You cannot use the menu pop-up that appears on the long tab.

Currently, the menu disappears immediately and single-tap events are being invoked.

![img_418a9911d4d5-1](https://user-images.githubusercontent.com/1860205/48111179-a91b2b00-e293-11e8-8704-31dfa87c11ff.jpeg)

**Comment by mmenu-mantano** [comment]
It should be fixed by now (at least on `develop`). Feel free to re-open the issue if it's not the case.
