### ISSUE TITLE
Possible memory leaks from webview 

### ISSUE THREAD

**Issue by ehapmgs** [readium/r2-navigator-swift#40]
I was running the test app i have noticed that after opening some epub and navigating between chapters (webviews) that the memory kept increasing as you see in the picture even tho after navigating back to the main screen

![Screen Shot 2019-04-17 at 7 44 54 PM](https://user-images.githubusercontent.com/26691494/56305984-1471fe80-614a-11e9-8f1e-4f7c38cf2bac.png)

looking at safari develop tab it seems all the previous webviews loaded in the app 

![Screen Shot 2019-04-17 at 7 46 22 PM](https://user-images.githubusercontent.com/26691494/56306043-41261600-614a-11e9-8909-335b28fa2e4c.png)

and in the memory graph debugger i have noticed the webviews still allocating memory 

![Screen Shot 2019-04-17 at 7 47 15 PM](https://user-images.githubusercontent.com/26691494/56306173-80ecfd80-614a-11e9-931f-8e9ad503e551.png)

and deinit never being called in WebView class, can you advice on this ?

**Comment by mmenu-mantano** [comment]
It's a known issue (although it was not reported) that I planned to tackle in the next few days. But if you have any clues on the cause of the leak before I start, any information is welcome. ;)

**Comment by mmenu-mantano** [comment]
@ehapmgs This PR fixes the leak: https://github.com/readium/r2-navigator-swift/pull/41 It should be merged in `develop` in the next couple of days.

**Comment by ehapmgs** [comment]
Thanks @mmenu-mantano, doing the same tests above the issue seems to be fixed
