### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by mboGraf** [readium/r2-navigator-swift#77]
Hello. This issue is really simple one. I have couple of trivial compile errors then try to build project in Xcode 11 with new 5.1 Swift compiler which prevents me to use the framework as Carthage dependency.

It's seems like `pdfView.canGoToNextPage()` and `pdfView.canGoToPreviousPage()` couldn't be used as methods any more. Just try it by yourself.

Thanks

**Comment by luckyzhangx** [comment]
+1. waiting for fixing.

**Comment by aferditamuriqi** [comment]
fixes are merged into develop
